on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  hello_world_job:
  
    runs-on: ubuntu-latest
  
    name: A job to say hello
    steps:

    - name: Hello world action step
      id: hello
      run: echo "Hello Ramesh ! Howdy !"
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
